version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@testing-library/react-hooks"
    versions:
    - 5.0.3
    - 5.1.0
    - 5.1.1
  - dependency-name: typescript
    versions:
    - 3.9.7
    - 3.9.8
  - dependency-name: rollup-plugin-typescript2
    versions:
    - 0.29.0
  - dependency-name: lodash
    versions:
    - 4.17.20
